// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTX8feb7JciLRcMpzISJDUjRWRo57XxkY',
    appId: '1:583751085628:web:363db814f62e525f50dd39',
    messagingSenderId: '583751085628',
    projectId: 'feedback-work-61234',
    authDomain: 'feedback-work-61234.firebaseapp.com',
    databaseURL: 'https://feedback-work-61234-default-rtdb.firebaseio.com',
    storageBucket: 'feedback-work-61234.firebasestorage.app',
    measurementId: 'G-18GL8LD6DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU--w1Wl10FbuPGjhqouaWQ57bpSQKHmg',
    appId: '1:583751085628:android:8d651b13c123500250dd39',
    messagingSenderId: '583751085628',
    projectId: 'feedback-work-61234',
    databaseURL: 'https://feedback-work-61234-default-rtdb.firebaseio.com',
    storageBucket: 'feedback-work-61234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zOpVCY33ZCLcd4QrqbdayrGuOPpYh5w',
    appId: '1:583751085628:ios:1496d40a57c1e0b350dd39',
    messagingSenderId: '583751085628',
    projectId: 'feedback-work-61234',
    databaseURL: 'https://feedback-work-61234-default-rtdb.firebaseio.com',
    storageBucket: 'feedback-work-61234.firebasestorage.app',
    iosBundleId: 'com.speaklogic.feedbackWork',
  );
}
